### ISSUE TITLE
Config Error in sphinx build

### ISSUE THREAD

**Issue by bheavner** [kids-first/kf-utils-python#30]
**Describe the bug**
When I follow the install instructions and run `sphinx-autobuild docs/ build -p 8000` I get an error: 
Configuration error:
There is a programmable error in your configuration file:

The server seems to start, but then after I visit 127.0.0.1:8000, I get a 404 error.

**Additional info**
Here's the traceback:
```
Traceback (most recent call last):
  File "/Users/heavner/virtualenv/kf_dev_handbook/lib/python3.9/site-packages/sphinx/config.py", line 327, in eval_config_file
    execfile_(filename, namespace)
  File "/Users/heavner/virtualenv/kf_dev_handbook/lib/python3.9/site-packages/sphinx/util/pycompat.py", line 88, in execfile_
    exec(code, _globals)
  File "/Users/heavner/Projects/kf-developer-handbook/docs/conf.py", line 53, in <module>
    from recommonmark.parser import CommonMarkParser
  File "/Users/heavner/virtualenv/kf_dev_handbook/lib/python3.9/site-packages/recommonmark/parser.py", line 6, in <module>
    from CommonMark import DocParser, HTMLRenderer
  File "/Users/heavner/virtualenv/kf_dev_handbook/lib/python3.9/site-packages/CommonMark/__init__.py", line 3, in <module>
    from CommonMark.CommonMark import HTMLRenderer
  File "/Users/heavner/virtualenv/kf_dev_handbook/lib/python3.9/site-packages/CommonMark/CommonMark.py", line 18, in <module>
    HTMLunescape = html.parser.HTMLParser().unescape
AttributeError: 'HTMLParser' object has no attribute 'unescape'
```

**Comment by fiendish** [comment]
I think you filed this on the wrong repository. There's no docs directory in kf-utils-python.
